### ISSUE TITLE
No document found for rule about @typescript-eslint

### ISSUE THREAD

**Issue by iwata** [sindresorhus/eslint-formatter-pretty#41]
I'm using [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin).
So the following error occurred.

```
Error: No documentation found for rule
    at module.exports (/Users/iwata/.go/src/github.com/bm-sms/nomos/admin/node_modules/eslint-formatter-pretty/node_modules/eslint-rule-docs/index.js:16:11)
    at lines.map.x (/Users/iwata/.go/src/github.com/bm-sms/nomos/admin/node_modules/eslint-formatter-pretty/index.js:113:80)
    at Array.map (<anonymous>)
    at module.exports.results (/Users/iwata/.go/src/github.com/bm-sms/nomos/admin/node_modules/eslint-formatter-pretty/index.js:97:18)
    at log (/Users/iwata/.go/src/github.com/bm-sms/nomos/admin/node_modules/xo/cli-main.js:138:23)
    at xo.lintFiles.then.report (/Users/iwata/.go/src/github.com/bm-sms/nomos/admin/node_modules/xo/cli-main.js:183:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

When I output the `pluginName` at the error part, it is displayed as `@typescript-eslint`. Is this problem caused by `eslint-rule-docs` being old?
Please tell me if there is workaround.

**Comment by sindresorhus** [comment]
The crash was already fixed: https://github.com/sindresorhus/eslint-formatter-pretty/commit/ed9f2d6ac03e7359c6ddc9a49570ddbe496d6b10 Just reinstall.

As for missing docs for that plugin, see: https://github.com/stefanbuck/eslint-rule-docs/issues/4
